package com.classhub.notification;

public enum NotificationType {
    COURSEWORK_PUBLISHED,
    ANNOUNCEMENT_PUBLISHED,
    COURSEWORK_DEADLINE_REMINDER,
    COURSEWORK_DEADLINE_CHANGED,
    COURSEWORK_CANCELLED,
    COURSEWORK_INSTRUCTIONS_UPDATED
}
